<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="x100_wheel">
    <xacro:property name="wheel_kp" value="1000000.0" />
    <xacro:property name="wheel_kd" value="100.0" />
    <xacro:property name="wheel_mu1" value="100" />
    <xacro:property name="wheel_mu2" value="100" />
    <xacro:property name="wheel_slip1" value="0" />
    <xacro:property name="wheel_slip2" value="0" />
    <xacro:property name="wheel_mass" value="${scale * 1}" />
    <xacro:property name="wheel_inertia" value="${scale * 1e-3}" />
    <xacro:property name="wheel_x_offset" value="${base_x_offset + x100_length/2.0}" />
    <xacro:property name="wheel_y_offset" value="${x100_width/2.0 - wheel_length/2.0}" />
    <xacro:macro name="x100_wheel" params="wheel_prefix *joint_pose">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
				<mass value="2" />
				<origin xyz="0 0 0" />
                <inertia  ixx="0.02467" ixy="0" ixz="0" iyy="0.04411" iyz="0" izz="0.02467" />		
            </inertial>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                   <!-- mesh filename="package://x100_gazebo/meshes/X300_wheel.dae" scale="1 1 1"/ -->
                   <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
                </geometry>
                <surface>
                    <friction>
                    <fdir1>0 0 1</fdir1>
                    <kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
                    <kd>${wheel_kd}</kd>
                    <mu>${wheel_mu1}</mu>
                    <mu2>${wheel_mu2}</mu2>
                    <slip1>${wheel_slip1}</slip1>
                    <slip2>${wheel_slip2}</slip2>
                    </friction>
                </surface>
            </collision>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${M_PI/2}"/>
                <geometry>
                   <mesh filename="package://x100_gazebo/meshes/X300_wheel.dae" scale="1 1 1"/>
                </geometry>
            </visual>            
            
        </link>

        
        
        <joint name="${wheel_prefix}_wheel" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_prefix}_wheel_link"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 1 0" rpy="0 0 0"/>
        </joint>
        <transmission name="${wheel_prefix}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${wheel_prefix}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="${wheel_prefix}_wheel">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>
        
    </xacro:macro>
    
</robot>
